"""Add category to Paper and Payment model

Revision ID: 2a1179e0a3c5
Revises: 8c98ff6f339a
Create Date: 2026-04-23 20:47:16.631471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1179e0a3c5'
down_revision = '8c98ff6f339a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('card_last_four', sa.String(length=4), nullable=False),
    sa.Column('card_holder_name', sa.String(length=100), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('category')

    op.drop_table('payments')
    # ### end Alembic commands ###
