"""Added paper_views table

Revision ID: 354392ed17ca
Revises: 67d1805053f6
Create Date: 2026-03-20 19:17:42.472661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '354392ed17ca'
down_revision = '67d1805053f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('paper_view')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_view',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('paper_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('viewed_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('paper_view_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('paper_views')
    # ### end Alembic commands ###
