"""Add Annotation model

Revision ID: 8c98ff6f339a
Revises: 354392ed17ca
Create Date: 2026-04-23 20:07:50.091483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c98ff6f339a'
down_revision = '354392ed17ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('Critical', 'Major', 'Minor', 'Suggestion'), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('annotation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('paper_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('editor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('page_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('x_pos', mysql.FLOAT(), nullable=False),
    sa.Column('y_pos', mysql.FLOAT(), nullable=False),
    sa.Column('width', mysql.FLOAT(), nullable=False),
    sa.Column('height', mysql.FLOAT(), nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], name=op.f('annotation_ibfk_1')),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('annotation_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('annotations')
    # ### end Alembic commands ###
