"""ödeme durumu ve ücret sütunları eklendi

Revision ID: 93430e2d7250
Revises: 68f95d60690b
Create Date: 2026-02-21 14:06:17.591018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93430e2d7250'
down_revision = '68f95d60690b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('is_paid')

    # ### end Alembic commands ###
