"""status alani String yapildi

Revision ID: 184b8f21cbde
Revises: 28ad26d0d7a0
Create Date: 2026-02-21 12:52:53.452748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '184b8f21cbde'
down_revision = '28ad26d0d7a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('Submitted', 'Under Review', 'Revision Requested', 'Accepted', 'Rejected'),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('Submitted', 'Under Review', 'Revision Requested', 'Accepted', 'Rejected'),
               existing_nullable=True)

    # ### end Alembic commands ###
