"""review modeline yorum ve rapor sütunları eklendi

Revision ID: 68f95d60690b
Revises: 184b8f21cbde
Create Date: 2026-02-21 13:57:37.773635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f95d60690b'
down_revision = '184b8f21cbde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('report_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('report_path')
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
