"""Add Notification model, deadline fields, similarity_score

Revision ID: 910ecdc78998
Revises: f0398317f9f7
Create Date: 2026-05-24 19:57:05.295925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910ecdc78998'
down_revision = 'f0398317f9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('similarity_score', sa.Float(), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deadline_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('deadline_status')
        batch_op.drop_column('deadline')

    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('similarity_score')

    op.drop_table('notifications')
    # ### end Alembic commands ###
