"""Added abstract column to papers table

Revision ID: b3b32cc5d0ca
Revises: 93430e2d7250
Create Date: 2026-02-25 09:32:35.628055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b32cc5d0ca'
down_revision = '93430e2d7250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abstract', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('abstract')

    # ### end Alembic commands ###
